module.exports = {
  env: {
    browser: true,
    es2021: true,
  },
  extends: [
    'plugin:react/recommended',
    'airbnb',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  plugins: [
    'react',
    '@typescript-eslint',
  ],
  ignorePatterns: [
    'dist',
  ],
  rules: {
    '@typescript-eslint/semi': ['error', 'always'],
    '@typescript-eslint/member-delimiter-style': ['error', {
      multiline: {
        delimiter: 'semi',
        requireLast: true,
      },
      singleline: {
        delimiter: 'semi',
        requireLast: true,
      },
    }],
    '@typescript-eslint/no-empty-function': ['warn'],
    '@typescript-eslint/no-unused-vars': ['error'],
    '@typescript-eslint/no-shadow': ['error'],
    'react/state-in-constructor': ['off'],
    'react/jsx-filename-extension': ['off'],
    'react/jsx-one-expression-per-line': ['off'],
    'react/jsx-tag-spacing': ['error', {
      closingSlash: 'never',
      beforeSelfClosing: 'never',
      afterOpening: 'never',
      beforeClosing: 'never',
    }],
    'react/no-array-index-key': ['warn'],
    'react/function-component-definition': ['error', {
      namedComponents: 'arrow-function',
      unnamedComponents: 'arrow-function',
    }],
    'react/jsx-curly-brace-presence': ['error', {
      props: 'always',
      children: 'never',
    }],
    'react/destructuring-assignment': ['error', 'never'],
    'react/prop-types': ['off'],
    'react/jsx-no-useless-fragment': ['off'],
    'react/require-default-props': ['off'],
    'semi': ['off'],
    'quotes': ['error', 'single'],
    'import/prefer-default-export': ['off'],
    'import/no-unresolved': ['off'],
    'import/extensions': ['off'],
    'sort-imports': ['error', {
      ignoreCase: true,
      ignoreDeclarationSort: true,
      ignoreMemberSort: true,
      allowSeparatedGroups: false,
      memberSyntaxSortOrder: [
        'none',
        'multiple',
        'single',
        'all',
      ],
    }],
    'class-methods-use-this': ['off'],
    'quote-props': ['error', 'consistent-as-needed'],
    'prefer-promise-reject-errors': ['error'],
    'no-param-reassign': ['error'],
    'max-len': ['warn', 120],
    'no-empty-function': ['warn'],
    'no-unused-vars': ['off'],
    'no-void': ['off'],
    'no-shadow': ['off'],
    'no-plusplus': ['off'],
    'no-unused-expressions': ['off'],
    'no-useless-computed-key': ['off'],
    'linebreak-style': ['off'],
  },
};
